version: "3"
services:
  database:
    build: ./db
    environment:
      POSTGRES_USER: rh
      POSTGRES_PASSWORD: russianhackers
      PG_DATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: journaldb #creates a database called "journaldb"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
    database-data:



#By default, the only things removed are:

#  - Containers for services defined in the Compose file
#  - Networks defined in the `networks` section of the Compose file
#  - The default network, if one is used

# docker-compose down --volumes will delete the volumes
# this will make the docker-compose file rebuild the db (otherwise it uses old data)
