app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/journaldb
    username: rh
    password: russianhackers
    pool-size: 30
application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10