spring:
  datasource:
    username: rh
    password: russianhackers
    pool-size: 30
    jdbc-url: jdbc:postgresql://localhost:5432/journaldb
application:
  name: russianhackers
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10