app:
  datasource:
    jdbc-url: ${APP_DATASOURCE_JDBC_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    pool-size: 30
application:
  jwt:
    secretKey: ${APP_JWT_SECRETKEY}
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10